services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./data:/tmp
    environment:
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24